<table class="link" width="100%">
  <tr>
    <td class="color_1" width="200">&nbsp;</td>
    <td class="link">
      <a href="index.php">О кафедре</a>&nbsp;|&nbsp;<a href="index.php">История</a>&nbsp;|&nbsp;<a href="employees.php">Сотрудники</a>&nbsp;|&nbsp;<a href="studywork.php">Учебная работа</a>&nbsp;|&nbsp;<a href="nopage.php">Научная работа</a>&nbsp;|&nbsp;<a href="developments.php">Разработки кафедры</a>&nbsp;|&nbsp;<a href="nopage.php">Выпускники</a>
    </td>
  </tr>
</table>

