<table class="Main" align="center">
  <!--Page Head Start-->
  <tr><td class="HeadS" colspan="3">&nbsp;</td></tr>
  <!--Link-->
  <tr><td class="Link" colspan="3">
    <a href="index.php">Главная</a>&nbsp;|
    <a href="Tour.php">Туры</a>&nbsp;|
    <a href="Photo.php">Фотогалерея</a>&nbsp;|
    <a href="Luno.php">О нас</a>&nbsp;|
    <a href="Response.php">Отзывы</a>&nbsp;
  </td></tr>
  <!--Page Head End-->
  <tr><td class="HeadE" colspan="3">&nbsp;</td></tr>
  <!--Left Start-->
  <td class="LeftS">
    <table height="100%" width="100%">
      <tr>
        <td class="LeftS">
          <table class="LeftLink">
            <tr><td><a href="index.php">Главная</a></td></tr>
            <tr><td><a href="Tour.php">Туры</a></td></tr>
            <tr><td><a href="Photo.php">Фотогалерея</a></td></tr>
            <tr><td><a href="Luno.php">О нас</a></td></tr>
            <tr><td><a href="Response.php">Отзывы</a></td></tr>
          </table>
        </td>
      </tr>
      <tr>
        <td class="LeftE">&nbsp;</td>
      </tr>
    </table>
  </td>
  <!--Content Start-->
  <td class="Content" rowspan="2">



