<table align="center" height="100%" width="800" class="main" cellpadding="0" cellspacing="0">
  <tr><td height="124"><?php include "logo.inc";?></td></tr>
  <tr><td height="50"><?php include "link.inc";?></td></tr>
  <tr>
    <td>
      <table cellspacing="0" cellpadding="0" width="100%" height="100%">
        <tr>
          <td width="163"><?php include "NStart.inc"; include "news.inc"; include "NEnd.inc";?></td>
          <td><table cellspacing=5 cellpadding=0 width="100%"><tr><td>
